//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkBiddingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
    }
}
